# Generated by Django 2.1.4 on 2019-03-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acak_kata_apps', '0003_kata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kata',
        ),
    ]
