# Generated by Django 2.1.4 on 2019-03-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acak_kata_apps', '0005_kata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kata',
        ),
    ]
